### PR TITLE
Missing word 'sponsor' on bottom of front page.

### PR DESCRIPTION
**Pull request by karl-zylinski**
Thank you to everyone who Odin
->
Thank you to everyone who sponsor Odin

### CODE REVIEW

**Comment by Kelimion** [comment]
But what if we wanted to thank people who Odin?

**Comment by laytan** [comment]
Is it not "sponsors Odin"?

**Comment by karl-zylinski** [comment]
Googled around a bit and both seem to work. Both sound OK in my head too. But if it is wrong, then please do change it.

**Comment by laytan** [comment]
English is weird :p

**Pull request merged**
