### PR TITLE
Add wgpu to vendor section on the landing page

### PR DESCRIPTION
**Pull request by thetarnav**
image

image

### CODE REVIEW

**Comment by gingerBill** [comment]
The WebGPU logo needs to look good in dark mode too.

**Comment by thetarnav** [comment]
just the mark looks good in both light and dark modes

image

otherwise to have the logotype, there would have to be two images, switched between based on the dark-mode class?

**Comment by thetarnav** [comment]
had to inline the logo to modify it with a new `dark-mode-fill-white` class

image

image

**Comment by gingerBill** [comment]
Wonderful!

**Pull request merged**
